python main.py --env_name=visual-antmaze-medium-navigate-v0 --train_steps=500000 --eval_episodes=50 --agent=agents/csiq.py --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-large-navigate-v0 --train_steps=500000 --eval_episodes=50 --agent=agents/csiq.py --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-giant-navigate-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.3 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-teleport-navigate-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-medium-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-large-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-giant-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.3 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-teleport-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.3 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-medium-explore-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=1.0 --agent.actor_p_trajgoal=0.0 --agent.alpha=0.01 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-large-explore-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=1.0 --agent.actor_p_trajgoal=0.0 --agent.alpha=0.01 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-antmaze-teleport-explore-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=1.0 --agent.actor_p_trajgoal=0.0 --agent.alpha=0.01 --agent.batch_size=256 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-medium-navigate-v0 --train_steps=500000 --eval_episodes=50 --agent=agents/csiq.py --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-large-navigate-v0 --train_steps=500000 --eval_episodes=50 --agent=agents/csiq.py --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-giant-navigate-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-medium-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-large-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-humanoidmaze-giant-stitch-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_p_randomgoal=0.5 --agent.actor_p_trajgoal=0.5 --agent.alpha=0.1 --agent.batch_size=256 --agent.discount=0.995 --agent.encoder=impala_small
python main.py --env_name=visual-cube-single-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-double-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-triple-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-quadruple-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-single-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-double-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-triple-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-cube-quadruple-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-scene-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-scene-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-3x3-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x4-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x5-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x6-play-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=1.0 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-3x3-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x4-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x5-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=visual-puzzle-4x6-noisy-v0 --train_steps=500000 --eval_episodes=50 --eval_on_cpu=0 --agent=agents/csiq.py --agent.alpha=0.03 --agent.batch_size=256 --agent.encoder=impala_small --agent.p_aug=0.5
python main.py --env_name=powderworld-easy-play-v0 --train_steps=500000 --eval_episodes=50 --eval_temperature=0.3 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_loss=awr --agent.alpha=3.0 --agent.batch_size=256 --agent.discrete=True --agent.encoder=impala_small
python main.py --env_name=powderworld-medium-play-v0 --train_steps=500000 --eval_episodes=50 --eval_temperature=0.3 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_loss=awr --agent.alpha=3.0 --agent.batch_size=256 --agent.discrete=True --agent.encoder=impala_small
python main.py --env_name=powderworld-hard-play-v0 --train_steps=500000 --eval_episodes=50 --eval_temperature=0.3 --eval_on_cpu=0 --agent=agents/csiq.py --agent.actor_loss=awr --agent.alpha=3.0 --agent.batch_size=256 --agent.discrete=True --agent.encoder=impala_small
